# Generated by Django 2.2.13 on 2020-06-08 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_fghjtu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hhtkuytuy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jgfjhf', models.BigIntegerField()),
            ],
        ),
    ]
